### ISSUE TITLE
version contraints won't allow use

### ISSUE THREAD

**Issue by mvilain** [JamesWoolfenden/terraform-linode-instance#1]
I added the [https://registry.terraform.io/modules/JamesWoolfenden/instance/linode/latest](code on terraform site) and I think Hashicorp changed the syntax. There's also an extraneous "." after the version tag which is no longer allowed.  Once I cleaned that up, I got the following errors when doing **terraform init**:

```
14:38:23 [dexlabs-2 289 ~/gitlab/tf/linode]$ terraform init
Initializing modules...
Downloading github.com/JamesWoolfenden/terraform-linode-instance for instance...
- instance in .terraform/modules/instance

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of linode/linode from the dependency lock file
- Finding hashicorp/tls versions matching "3.0.0"...
- Finding hashicorp/random versions matching "3.0.0"...
- Finding hashicorp/local versions matching "2.0.0"...
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)
- Installing hashicorp/local v2.0.0...
- Installed hashicorp/local v2.0.0 (signed by HashiCorp)
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)
│
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider linode/linode: locked provider registry.terraform.io/linode/linode 1.16.0 does not
│ match configured version constraint 1.13.4, 1.16.0; must use terraform init -upgrade to allow selection of new versions
│

14:38:46 [dexlabs-2 290 ~/gitlab/tf/linode]$ terraform init -upgrade
Upgrading modules...
Downloading github.com/JamesWoolfenden/terraform-linode-instance for instance...
- instance in .terraform/modules/instance

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/local versions matching "2.0.0"...
- Finding linode/linode versions matching "1.13.4, 1.16.0"...
- Finding hashicorp/tls versions matching "3.0.0"...
- Finding hashicorp/random versions matching "3.0.0"...
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)
- Installing hashicorp/local v2.0.0...
- Installed hashicorp/local v2.0.0 (signed by HashiCorp)
│
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider linode/linode: no available releases match the given constraints 1.13.4, 1.16.0
╵
```

Can you review the updated dependencies and revise the hashicorp entry?  I'll look at the code itself and see if I can get it working without using the github version.

**Comment by JamesWoolfenden** [comment]
I think the issue is the 2 different version specified for linode modules:
- Finding linode/linode versions matching "1.13.4, 1.16.0".

I had to add 2 terraform.tf to the module and example (only one should be there but i had issues with that).
They do need to be the same version and you are using different ones.

**Comment by JamesWoolfenden** [comment]
tf init -upgrade
Upgrading modules...
Downloading JamesWoolfenden/instance/linode 0.0.6 for instance...
- instance in .terraform/modules/instance

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/local versions matching "2.0.0"...
- Finding hashicorp/tls versions matching "3.0.0"...
- Finding hashicorp/random versions matching "3.0.0"...
- Finding linode/linode versions matching "1.16.0"...
- Installing linode/linode v1.16.0...
- Installed linode/linode v1.16.0 (signed by a HashiCorp partner, key ID F4E6BBD0EA4FE463)
- Using hashicorp/local v2.0.0 from the shared cache directory
- Using hashicorp/tls v3.0.0 from the shared cache directory
- Using hashicorp/random v3.0.0 from the shared cache directory

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
➜  exampleversion git:(master) pwd
/mnt/f/Code/modules/linode/terraform-linode-instance/example/exampleversion
